services:
  postgres_db:
    image: postgres:latest
    container_name: business_tracker_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_DB: ${POSTGRESQL_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  mssql_db:
    image: mcr.microsoft.com/azure-sql-edge:latest # for MacOS with M chip
    container_name: business_tracker_mssql
    hostname: mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_PASS}
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/backup