// <auto-generated />
using System;
using BusinessTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessTracker.Data.Migrations
{
    [DbContext(typeof(BusinessTrackerContext))]
    partial class BusinessTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessTracker.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("Categories_pkey");

                    b.HasIndex("OwnerId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            Name = "Продукты питания",
                            OwnerId = new Guid("a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11")
                        });
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Employees_pkey");

                    b.HasIndex("OwnerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            Name = "Иван Иванов",
                            OwnerId = new Guid("a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            PhoneNumber = "+79991234567",
                            Role = 1
                        });
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.JournalRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("CategoryCode")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<int?>("EmployeeCode")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("NomenclatureName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<long?>("ProductCode")
                        .HasColumnType("bigint");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("RawId")
                        .HasColumnType("integer");

                    b.Property<int>("RawLoginId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TransTypeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("JournalRows_pkey");

                    b.HasIndex("OrganizationId");

                    b.ToTable("JournalRows");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.LinksUserOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("LinksUserOrganizations_pkey");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("LinksUserOrganizations");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("Nomenclatures_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nomenclatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            CategoryId = new Guid("c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            Name = "Хлеб пшеничный"
                        });
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LoadOptions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("Organizations_pkey");

                    b.HasIndex(new[] { "Inn" }, "OrganizationInnIx")
                        .IsUnique();

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            Address = "190000, Ленинградская обл., Ломоносовский р-н, г. Ломоносов, ул. Советская, д. 12",
                            Inn = "1234567890",
                            Name = "Главный офис (Спб)"
                        },
                        new
                        {
                            Id = new Guid("a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12"),
                            Address = "230000, Иркутская обл., Октябрьский р-н, г. Иркутск, ул. 3 Июля, д. 3",
                            Inn = "0987654321",
                            Name = "Филиал (Иркутск)"
                        });
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Transactions_pkey");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"),
                            Name = "Администратор",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Category", b =>
                {
                    b.HasOne("BusinessTracker.Data.Models.Organization", "Owner")
                        .WithMany("Categories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Categories_Organizations");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Employee", b =>
                {
                    b.HasOne("BusinessTracker.Data.Models.Organization", "Owner")
                        .WithMany("Employees")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Organizations");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.JournalRow", b =>
                {
                    b.HasOne("BusinessTracker.Data.Models.Organization", "Owner")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JournalRows_Organizations");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.LinksUserOrganization", b =>
                {
                    b.HasOne("BusinessTracker.Data.Models.Organization", "Organization")
                        .WithMany("LinksUserOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LinksUserOrganizations_Organizations");

                    b.HasOne("BusinessTracker.Data.Models.User", "User")
                        .WithMany("LinksUserOrganizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LinksUserOrganizations_Users");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Nomenclature", b =>
                {
                    b.HasOne("BusinessTracker.Data.Models.Category", "Category")
                        .WithMany("Nomenclatures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nomenclatures_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Transaction", b =>
                {
                    b.HasOne("BusinessTracker.Data.Models.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Employees");

                    b.HasOne("BusinessTracker.Data.Models.Nomenclature", "Nomenclature")
                        .WithMany("Transactions")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Nomenclatures");

                    b.HasOne("BusinessTracker.Data.Models.Organization", "Owner")
                        .WithMany("Transactions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Organizations");

                    b.Navigation("Employee");

                    b.Navigation("Nomenclature");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Category", b =>
                {
                    b.Navigation("Nomenclatures");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Employee", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Nomenclature", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.Organization", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Employees");

                    b.Navigation("LinksUserOrganizations");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BusinessTracker.Data.Models.User", b =>
                {
                    b.Navigation("LinksUserOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
